### ISSUE TITLE
Linux WebServer to host visualization and connect to CX via ADS

### ISSUE THREAD

**Issue by PetraNIC** [Beckhoff/ADS#28]
Hello!

For our visualization we currently always use the WebServer on CX (CX8090 or CX9020 with WinCE). There is both - the TcAdsWebService.dll and our visualization (NO php or asp - only html and js). The access (read / write) then takes place via ADS - TAME 3 (http://tomcx.github.io/tame3/). The visualization is called from Firefox (on Windows) or on a Linux-touch display (Garz & Fricke) or from an Android / iOS Phone in the network.

So far so good. Now we have a requirement that we do not use the WebServer on CX, but the one on a Linux-touch panel PC. The aim should therefore be, to host the visualization and the AdsWebService (?) on Linux and then again from the visualization via JavaScript via WebService (?) to gain access to CX via ADS.
- is that possible?
- What is needed to prepare a route between CX and Linux (is probably necessary ?!)?
- is there an equivalent to TcAdsWebService.dll?
- Which libraries etc. are necessary?

The touch panel is a device made by Hainzl from Linz (http://www.hainzl.at/de).
- WebServer nginx 1.10.0
- Linux kernel version: Linux mmi13 3:16:35 # 1 SMP PREEMPT Tue Jun 28 09:56:37 CEST 2016 armv7l GNU / Linux

Thanks for your support!

regards
Petra Niederkofler

PS: 
Attached you find a list of installed packages:
[packages.txt](https://github.com/Beckhoff/ADS/files/359198/packages.txt)

**Comment by xift** [comment]
Hi Petra,

first thing: I am in no way affiliated with Beckhoff. Nor have I used the AdsWebService component before. So what follows is just a solution that popped into my head reading your post.

As far as I know you will not be able to use the AdsWebService component on a linux system. The AdsWebService software package is an ISAPI-DLL deployed using Microsoft IIS. There is no chance you can use that exact component on a linux system. Since TAME 3 relies on the WebService-API you will not be able to use TAME for your visualization either.

So here is what you can do:
Use the library from this repository to create a websocket server which provides an API to read and write ADS variables from your CX system. An easy to use websocket library would be https://github.com/zaphoyd/websocketpp. Websockets could be replaced by AJAX as well... For some reason I feel more comfortable with the websocket protocol. 

So your system could look like this:
![structure](https://cloud.githubusercontent.com/assets/1312047/16781283/c5f7282e-487a-11e6-994c-8e539f250834.PNG)

Anyway. This looks like a bit of effort is required. Maybe someone from Beckhoff can show you an easier way. 

Best of luck!
Michael

By the way, I'm not quite sure if this is the right place to post a question like this since the repository has nothing to do with the AdsWebService.
