### ISSUE TITLE
ADS,AMS,Net ID architecture

### ISSUE THREAD

**Issue by TamakiAutomation** [Beckhoff/ADS#66]
I'm trying to connect CX2020 to Linux PC.
But I'm confusing about relationship ADS, AMS, Net ID.

CX2020 has following 5 different netID.
![image](https://user-images.githubusercontent.com/38831582/39506955-bd43982c-4e16-11e8-8692-e5f7ffd4f8e9.png)

ADS service port
![image](https://user-images.githubusercontent.com/38831582/39507133-8be42cdc-4e17-11e8-946c-e6cb2de8c1fa.png)

Now I could connect Device2 via ADS, however I coulndn't connect other NetID and Port like 851.
As a Question,
1.How Could I change Target NetID?
2.How many Message Router exists in CX2020? 
3.If several router are, how is the releationship? 

Futhermore, each Device has ADS server. Where it is located?

I would like to make a simple fig for this architecture and put here.

Thank you

**Comment by TamakiAutomation** [comment]
For the firsrt, I'll put current understanding. Maybe it should be wrong.
![ads1](https://user-images.githubusercontent.com/38831582/39501137-0cd23ec0-4df4-11e8-9036-2ec1dc96166a.png)
Square filled by grey is destination which has global variables.

**Comment by pbruenn** [comment]
I am not an expert on ADS, it's architecture or use cases. All I know and did is this simple ADS client library, so take my response with care.

"I'm trying to connect CX2020 to Linux PC." sounds like you want to connect TwinCAT to your PC running this Open Source library. This will not work. This library is not able to run a ADS device (server), because the "Message Router" is not a real one. It is limited to map destination AmsAddresses (NetId + AmsPort) to TCP/IP connections. It is like a "one-way" routing. 

If you run TwinCAT on your CX2020 you have one full functional "Message Router" with multiple ADS devices connected. This might help to understand ADS better:
https://infosys.beckhoff.com/content/1033/tcadscommon/html/tcadscommon_intro.htm
https://infosys.beckhoff.com/content/1033/tc3_adscommon/html/tcadscommon_introtc3.htm?id=77839136258212880

To answer your questions:
0. ADS is an application layer on top of AMS. An ADS device is a virtual device node identified by an AMS address (AmsAddr) which consists of an AmsNetId and AmsPort number. A TwinCAT3 PLC is typically an ADS device running on AmsPort 851.
1. Depends on what you mean by target:
- you can change the local AmsNetId of your PC running this Open Source AdsLib with:
https://github.com/Beckhoff/ADS/blob/7758220f831e295d45d4dcffc79c8bbfdde666f5/AdsLib/AdsLib.h#L71
- on your TwinCAT system it should be straightforward. Right click on the TwinCAT tray icon->router->Change AMS NetId
2. There is only one "Message Router" on your CX2020 (TwinCAT)
