### ISSUE TITLE
Connection closed during plc online view (tc2)

### ISSUE THREAD

**Issue by mriepl** [Beckhoff/ADS#74]
When i have a valid connection to the plc and i login from plc controll to my cx5020 the connection will be closed with the info "connection closed by remote" is this normal?

best regards
markus

**Comment by pbruenn** [comment]
In case you run your TwinCAT Online View on the same host (IP address) as your AdsLib application, that is indeed expected behaviour.
Short answer: Either use TcAdsDll.dll shipped with your TwinCAT instead of this open source library or use two seperate machines for your AdsLib application and PLC online view
If you want to read about the details, check this issue https://github.com/Beckhoff/ADS/issues/30

Regards,
Patrick
